### ISSUE TITLE
Retrieve potentially scammy prompts from an API

### ISSUE THREAD

**Issue by ribru17** [gang21/CS130-Capstone-Project#5]
## Detailed Description
We want to pull (potentially) scammy messages from an API so that we don't have to write them ourselves. These will be displayed to the user on the cards, and they will then swipe left or right depending on whether or not they think the scenario is a scam. We also need to pull non-scammy scenarios from an API (not strictly the same one).

## Acceptance Criteria
- [x] When the user arrives on the play plage, the frontend should requests 10 random exercises to the backend
- [x] Results must be pulled from an API of our choosing
- [x] #33 
- [x] #37

## Associated Epic
- #1

**Comment by annaellebgt** [comment]
#37
